### ISSUE TITLE
make some blapy requests on page load

### ISSUE THREAD

**Issue by Sparkxxx** [intersel/Blapy#2]
Hi, 

Thanks for Blapy which is amaizing when you don't want to mess with javascripts and stuff (which I don't know much about anyway). 
I got Blapy to work on some blocks and php but I would like that the content of the blocks is automatically updated when the page is loaded, index.html which now has to have static content since I don't know how to make it self update the blocks onload, is this possible?

Thank you.

**Comment by intersel** [comment]
Hi,
Thanks to use Blapy!

The idea is to directly call the url that will initialize your page by calling one of the Blapy API functions "loadURL" or "postData" just after the Blapy initialization.

Example:

```
$( document ).ready(function() {
    $('#myBlapy').Blapy();
    $('#myBlapy').trigger('loadUrl',{aUrl:"init_my_page.php"})
});
```

**Comment by Sparkxxx** [comment]
Thank you very much

Just tried it and it works like a charm, I love Blapy.
Is there any way I could also make it reload itself on a regular interval and simulate with this like a websockets connection?

Thank you again

**Comment by intersel** [comment]
For now, there is no configuration to set such behaviour in Blapy.
The way to do it is to use the standard javascript setInterval:

setInterval(function(){
   $('#myBlapy').trigger('loadUrl',{aUrl:"update_my_page.php"}); 
}, 3000);

**Comment by intersel** [comment]
I just integrated a new feature just to do that: now you have two more attributes "data-blapy-href " and "data-blapy-updateblock-time"  that let you configure the URL to call and the period to call it

This example will update the block every second (1000ms) from index.php:

``` html
    <div id="myBlapy">
        <div    data-blapy-container="true" 
                        data-blapy-container-name="dateContainer" 
                        data-blapy-container-content="aContent_<?php echo time();?>" 
                        data-blapy-href = "index.php"
                        data-blapy-updateblock-time = "1000"
                >
                    <b>Time is:</b> <?php echo date('d-M-Y H:i:s');?>
        </div>
    </div>
```

**Comment by Sparkxxx** [comment]
Thank you very much intersel this will make the page really dynamic and with the auto update on page load makes Blapy a wonderful tool for those who don't know Javascript.
Thank you 

Sent from my Samsung device

-------- Original message --------
